import React from 'react';

const Home=()=>{
    return (
        <div>
        <h1 className="header">Home Page</h1>
        <p>Lorem, ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id laborum inventore! Eum, expedita unde doloremque hic quam beatae, nemo cumque corrupti ipsam consequuntur perferendis culpa quidem fugiat fugit laudantium! Dolorem atque laboriosam maxime accusamus, voluptate at u
        llam nam vel tempora hic, eaque distinctio illum debitis? Molestias velit, aliquid commodi at expedita deleniti. Deserunt mollitia perspiciatis libero quasi aut unde quas quos magnam sequi autem eum sunt molestiae dolor rem iste amet, nam laudantium similique solu
        ta, dolores totam illo! Cumque tenetur blanditiis quas dicta voluptate alias non libero Lorem ipsum dolo
        r sit amet, consectetur adipisicing elit. Optio beatae inventore voluptate alias suscipit vero neque consectet
        ur, modi sequi laborum laboriosam, excepturi natus officiis repellat soluta veniam ullam culpa! Atque, maiores! 
        Velit, aspernatur dicta. iure illos, libero pariaolor sit amet, consectetur adipisicing elit. Itaque excepturi sequi amet nesciunt quidem. Blanditiis commodi magnam placeat debitis fugit. Blanditiis a at omnis et dolor ut ducimus veniam, porro consequatur dolorum quae ab dolorem eos aspernatur laudantium officia impedit recusandae vero cum assumenda perferendis autem! Dolores commodi in autem iusto nihil suscipit vero molestiae? Architecto suscipit sapiente similique tempora possimus? Inventore sint mollitia recusandae quas dolor eveniet est ipsum illo ea sunt voluptatum dicta possimus laudantium sequi, culpa quaerat voluptatem dolorum odit placeat molestiae minima aspernatur perspiciatis qui modi. Quisquam reprehenderit nesciunt quia pariatur incidunt impedit repellat, ut harum delectus, numquam at cupiditate id eos omnis vitae dolor perferendis dolorum deserunt quos eligendi dicta? Id impedit vitae qui fugit veniam illo mollitia consectetur molestias voluptate, expedita consequuntur inventore ipsa. Nulla ipsa dolor neque praesentium necessitatibus officia qui quae ipsam similique libero repudiandae voluptas est saepe quasi voluptatibus sunt modi porro quidem vel, itaque, incidunt illum iure. Ducimus odit fugit eos dolore officiis, pariatur hic, nostrum veniam adipisci, tenetur saepe recusandae nam fugiat earum ex. Voluptatem nemo maxime, nostrum porro reiciendis labore tempore? Incidunt consequuntur beatae quaerat vitae laborum quisquam ratione expedita cumque quibusdam alias, saepe quis veritatis doloribus rem optio? Enim possimus quidem repudiandae beatae ipsa nihil laborum perspiciatis labore, eius maiores quas! Libero fuga iusto, a provident nulla eius non beatae ipsam impedit facere. Temporibus maxime voluptates quisquam assumenda odio neque accusamus iure iste, odit facilis alias eos autem praesentium ipsa perspiciatis rerum debitis aperiam tempora. Ratione odit enim quibusdam explicabo esse! Necessitatibus maiores quibusdam ad, rem adipisci recusandae commodi temporibus eligendi eveniet architecto dolore nemo? Consectetur dignissimos reprehenderit debitis quia facilis ducimus illum, minima rem recusandae dolor nobis ad iure consequatur dolorem odit tenetur rerum assumenda maiores. Earum odio excepturi voluptatibus,
         perferendis suscipit ratione minus inventore reiciendis? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora sapiente nulla rerum consequuntur cum excepturi quam reprehenderit mollitia hic. Dicta quidem eligendi asperiores nobis 
         accusamus dignissimos, libero pariatur quaerat aliquam!tur quaerat !</p>
        
        </div>
    ) 
}
export default Home;